# Generated by Django 4.2.7 on 2023-12-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fTable',
            fields=[
                ('farmerID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('fname', models.CharField(blank=True, max_length=30)),
                ('lname', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('house', models.CharField(blank=True, max_length=50)),
                ('street', models.CharField(blank=True, max_length=50)),
                ('thana', models.CharField(blank=True, max_length=50)),
                ('zip', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('contactnumber', models.CharField(blank=True, max_length=15)),
                ('supplierType', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
