# Generated by Django 4.2.7 on 2023-12-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ftable',
            name='supplierType',
        ),
    ]
