# Generated by Django 4.2.7 on 2023-12-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0002_remove_ftable_suppliertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
