# Generated by Django 4.2.7 on 2023-12-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upper_Price', models.IntegerField(default=0)),
                ('Lower_Price', models.IntegerField(default=0)),
            ],
        ),
    ]
