# Generated by Django 4.2.7 on 2023-12-12 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pTable',
            fields=[
                ('productID', models.BigAutoField(primary_key=True, serialize=False)),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productName', models.CharField(max_length=30)),
                ('supplierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.stable')),
            ],
        ),
    ]
