# Generated by Django 4.2.7 on 2023-12-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('supplier', 'Supplier'), ('farmer', 'Farmer'), ('ARDOFFICER', 'ARDOFFICER')], max_length=20, null=True, verbose_name='User Type'),
        ),
    ]
