# Generated by Django 4.2.7 on 2023-12-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bug',
            fields=[
                ('id', models.IntegerField(default=784, primary_key=True, serialize=False)),
                ('user', models.CharField(default='Hasib', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
            ],
        ),
    ]
