# Generated by Django 4.2.7 on 2023-12-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TestProduct',
            fields=[
                ('productID', models.BigAutoField(primary_key=True, serialize=False)),
                ('supplierID', models.IntegerField(null=True)),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productName', models.CharField(max_length=30)),
            ],
        ),
    ]
