# Generated by Django 4.2.7 on 2023-12-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bug2',
            fields=[
                ('id', models.IntegerField(default=784, primary_key=True, serialize=False)),
                ('user', models.CharField(default='Farmer', max_length=30)),
            ],
        ),
    ]
