# Generated by Django 4.2.7 on 2023-12-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_product_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer_Offered_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmerID', models.CharField(max_length=100)),
                ('ProductID', models.CharField(max_length=100)),
                ('AMROfficerID', models.CharField(max_length=100)),
                ('offeredPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
