# Generated by Django 4.2.7 on 2023-12-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_rename_lowerprice_set_price_lower_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set_price',
            name='Lower_Price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='set_price',
            name='Upper_Price',
            field=models.IntegerField(default=0),
        ),
    ]
