# Generated by Django 4.2.7 on 2023-12-12 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_alter_set_price_lower_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set_price',
            name='AMROfficerID',
        ),
        migrations.RemoveField(
            model_name='set_price',
            name='ProductID',
        ),
    ]
