# Generated by Django 4.2.7 on 2023-12-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_set_price_amrofficerid_set_price_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set_price',
            name='AMROfficerID',
        ),
        migrations.RemoveField(
            model_name='set_price',
            name='ProductID',
        ),
    ]
