# Generated by Django 4.2.7 on 2023-12-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_remove_set_price_amrofficerid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set_price',
            name='Lower_Price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='set_price',
            name='Upper_Price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
