# Generated by Django 4.2.7 on 2023-12-12 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_alter_product_supplierid_alter_set_price_lower_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ProductID',
            new_name='productID',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='supplierID',
            new_name='supplier',
        ),
    ]
