# Generated by Django 4.2.7 on 2023-12-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_rename_productid_product_productid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productID',
            new_name='ProductID',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.AddField(
            model_name='product',
            name='supplierID',
            field=models.IntegerField(default=101),
            preserve_default=False,
        ),
    ]
