# Generated by Django 4.2.7 on 2023-12-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_rename_productid_product_productid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplierID',
            field=models.IntegerField(),
        ),
    ]
