# Generated by Django 4.2.7 on 2023-12-13 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_remove_supplier_supplierid_alter_product_supplierid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('farmerID', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('contactNumber', models.CharField(max_length=20)),
                ('cropType', models.CharField(max_length=100)),
                ('livestockType', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='id',
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplierID',
            field=models.IntegerField(default=801, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmer_offered_price',
            name='AMROfficerID',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='farmer_offered_price',
            name='ProductID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='farmer_offered_price',
            name='farmerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.farmer'),
        ),
    ]
