# Generated by Django 4.2.7 on 2023-12-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_rename_set_price_price_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_control',
            name='AMROfficerID',
            field=models.IntegerField(default=1),
        ),
    ]
