# Generated by Django 4.2.7 on 2023-12-13 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0027_rename_productid_price_control_productid_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price_control',
            name='ProductID_id',
        ),
        migrations.RemoveField(
            model_name='price_control',
            name='id',
        ),
        migrations.AddField(
            model_name='price_control',
            name='ProductID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='my_app.product'),
            preserve_default=False,
        ),
    ]
