# Generated by Django 4.2.7 on 2023-12-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0028_remove_price_control_productid_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price_control',
            name='ProductID',
        ),
        migrations.AddField(
            model_name='price_control',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
