# Generated by Django 4.2.7 on 2023-12-13 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0030_remove_price_control_id_price_control_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_control',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price_control',
            name='ProductID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.product'),
        ),
    ]
