# Generated by Django 4.2.7 on 2023-12-13 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0031_price_control_id_alter_price_control_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price_control',
            name='id',
        ),
        migrations.AlterField(
            model_name='price_control',
            name='ProductID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='my_app.product'),
        ),
    ]
