# Generated by Django 4.2.7 on 2023-12-14 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0035_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_offered_price',
            name='AMROfficerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.price_control'),
        ),
    ]
