# Generated by Django 4.2.7 on 2023-12-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('house', models.CharField(max_length=12)),
                ('street', models.CharField(max_length=12)),
                ('thana', models.CharField(max_length=12)),
                ('zip', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=15)),
                ('contactnumber', models.CharField(max_length=15)),
                ('supplierType', models.CharField(choices=[('fertilizer', 'Fertilizer Supplier'), ('equipementandmachineries', 'Equipment And Machineries Supplier'), ('seed', 'Seed Supplier'), ('coldstorage', 'Cold Storage Supplier'), ('cattleandfisheries', 'Cattle And Fisheries Supplier')], max_length=50)),
                ('userType', models.CharField(default='Supplier', max_length=20)),
            ],
        ),
    ]
