# Generated by Django 4.2.7 on 2023-12-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suppliers',
        ),
    ]
