# Generated by Django 4.2.7 on 2023-12-12 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_farmer_offered_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='contactnumber',
            new_name='contactNumber',
        ),
    ]
