# Generated by Django 4.2.7 on 2023-12-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_rename_contactnumber_supplier_contactnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set_price',
            old_name='Lower_Price',
            new_name='lowerPrice',
        ),
        migrations.RenameField(
            model_name='set_price',
            old_name='Upper_Price',
            new_name='upperPrice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offeredPrice',
        ),
        migrations.AddField(
            model_name='product',
            name='supplierID',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set_price',
            name='AMROfficerID',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set_price',
            name='ProductID',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
