# Generated by Django 4.2.7 on 2023-12-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_rename_lower_price_set_price_lowerprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_offered_price',
            name='AMROfficerID',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='farmer_offered_price',
            name='ProductID',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='farmer_offered_price',
            name='farmerID',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductID',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplierID',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='set_price',
            name='AMROfficerID',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='set_price',
            name='ProductID',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='set_price',
            name='lowerPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='set_price',
            name='upperPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplierID',
            field=models.IntegerField(max_length=100),
        ),
    ]
