# Generated by Django 4.2.7 on 2023-12-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_farmer_offered_price_amrofficerid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set_price',
            old_name='lowerPrice',
            new_name='Lower_Price',
        ),
        migrations.RenameField(
            model_name='set_price',
            old_name='upperPrice',
            new_name='Upper_Price',
        ),
        migrations.AlterField(
            model_name='farmer_offered_price',
            name='AMROfficerID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='farmer_offered_price',
            name='ProductID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='farmer_offered_price',
            name='farmerID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplierID',
            field=models.IntegerField(),
        ),
    ]
