# Generated by Django 4.2.7 on 2023-12-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_remove_set_price_amrofficerid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='set_price',
            name='AMROfficerID',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='set_price',
            name='ProductID',
            field=models.IntegerField(default=1),
        ),
    ]
