# Generated by Django 4.2.7 on 2023-12-12 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_alter_set_price_lower_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplierID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.supplier'),
        ),
        migrations.AlterField(
            model_name='set_price',
            name='Lower_Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='set_price',
            name='Upper_Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
