# Generated by Django 4.2.7 on 2023-12-13 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_country_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='supplierID',
        ),
        migrations.AlterField(
            model_name='product',
            name='supplierID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.supplier'),
        ),
    ]
