# Generated by Django 4.2.7 on 2023-12-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_farmer_remove_product_id_remove_supplier_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Set_Price',
            new_name='PRICE_CONTROL',
        ),
    ]
