# Generated by Django 4.2.7 on 2023-12-13 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0022_price_control_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price_control',
            name='ProductID',
        ),
    ]
