# Generated by Django 4.2.7 on 2023-12-13 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0023_remove_price_control_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_control',
            name='ProductID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_app.product'),
            preserve_default=False,
        ),
    ]
