# Generated by Django 4.2.7 on 2023-12-13 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0026_price_control_productid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price_control',
            old_name='ProductID',
            new_name='ProductID_id',
        ),
    ]
