# Generated by Django 4.2.7 on 2023-12-13 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0032_remove_price_control_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price_control',
            name='AMROfficerID',
        ),
    ]
