# Generated by Django 4.2.7 on 2023-12-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0033_remove_price_control_amrofficerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_control',
            name='AMROfficerID',
            field=models.IntegerField(default=1),
        ),
    ]
