# Generated by Django 4.2.7 on 2023-12-16 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0036_alter_farmer_offered_price_amrofficerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_control',
            name='ProductID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='price_control', serialize=False, to='my_app.product'),
        ),
    ]
