# Generated by Django 4.2.7 on 2023-12-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otable',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
