# Generated by Django 4.2.7 on 2023-12-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_otable_totalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otable',
            name='totalPrice',
        ),
        migrations.AlterField(
            model_name='otable',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
