# Generated by Django 4.2.7 on 2023-12-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_remove_otable_totalprice_alter_otable_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='otable',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, default=1200, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otable',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
