# Generated by Django 4.2.7 on 2023-12-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_otable_totalprice_alter_otable_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='otable',
            name='address',
            field=models.CharField(default='Dhaka', max_length=500),
            preserve_default=False,
        ),
    ]
