# Generated by Django 4.2.7 on 2023-12-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testserver', '0002_testproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testproduct',
            name='prod_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='testproduct',
            name='supp_ID',
            field=models.IntegerField(null=True),
        ),
    ]
